### PR TITLE
Fixes coding style.

### PR DESCRIPTION
**Pull request by gmlwhdtjd**

### CODE REVIEW

**Comment by onmyway133** [comment]
@gmlwhdtjd Why do you prefer `self` in this case?

**Comment by gmlwhdtjd** [comment]
@onmyway133 In fact, it doesn't have an important meaning. Just, I matched the code of the other components. That use `self.getRed()` to get the value. So I think `self.getHue()` is better that `getHue()`.

**Comment by onmyway133** [comment]
@gmlwhdtjd Ah I see. I think `self.getRed()` is due to historical reasons. Now I think just `getRed` and `getHue` are more preferrable

**Comment by gmlwhdtjd** [comment]
Yes, I think so too. It doesn't need `self` at all.
How about this code?

**Comment by onmyway133** [comment]
@gmlwhdtjd Looks good to me 🚀

**Pull request merged**
