### PR TITLE
Update UIImage+Hue.swift

### PR DESCRIPTION
**Pull request by ZhipingYang**

### CODE REVIEW

**Comment by zenangst** [comment]
Travis is complaining that the label is missing.

`Source/iOS/UIImage+Hue.swift:109:57: missing argument label 'minSaturation:' in call`

**Comment by ZhipingYang** [comment]
@zenangst yeah I know, but this is required in swift3. may xcbuild should update?

**Comment by zenangst** [comment]
@ZhipingYang, yup but it is removed in your PR :)

**Comment by zenangst** [comment]
@ZhipingYang awesome, thanks mate!

**Pull request merged**
