### PR TITLE
Updated to Swift 5.0

### PR DESCRIPTION
**Pull request by rahimkhalid**

### CODE REVIEW

**Comment by rahimkhalid** [comment]
@onmyway133 can you kindly update the xcode version in Travis CI, as this pull request is for providing swift 5.0 support to your repo.

**Comment by onmyway133** [comment]
@zenangst your call 😄

**Comment by zenangst** [comment]
@rahimkhalid hey mate, thanks for doing this mate. However, the updating of the version being used on Travis is located in `.travis.yml`.

It should work if you change the `osx_image` to `osx_image: xcode10.2`

**Comment by rahimkhalid** [comment]
@zenangst thanks man (Y)

**Comment by zenangst** [comment]
@rahimkhalid thanks a lot for contributing mate! cheers!

**Pull request merged**
