### PR TITLE
Feature/carthage

### PR DESCRIPTION
**Pull request by vadymmarkov**
@zenangst 
1. Add framework project + Carthage support.
2. Re-configured travis (we have to see that it works :smiley: )

### CODE REVIEW

**Comment by RamonGilabert** [comment]
Failing... :smile:

**Comment by vadymmarkov** [comment]
I've changed travis configuration, so #yolo

**Comment by RamonGilabert** [comment]
So, should I merge? :smile:

**Comment by vadymmarkov** [comment]
Let's wait for @zenangst :smile:

**Comment by zenangst** [comment]
Yay, such success!

**Comment by zenangst** [comment]
@vadymmarkov fan-bloddy-tastic! :rainbow: :horse: :dizzy:

**Pull request merged**
